# Generated by Django 3.1 on 2021-11-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('tarif', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Servece',
                'verbose_name_plural': 'Serveces',
            },
        ),
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('stat', models.CharField(choices=[('submitted', 'Submitted'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client')),
                ('service', models.ManyToManyField(to='Article.Service')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
            options={
                'verbose_name': 'Artical',
                'verbose_name_plural': 'Articals',
            },
        ),
    ]
